integrations:
- name: nri-nginx
  env:
    METRICS: "true"
    # If you're using ngx_http_api_module be certain to use the full path up to and including the version number
    STATUS_URL: http://nginx:8080/status
    # Name of Nginx status module OHI is to query against. discover | ngx_http_stub_status_module | ngx_http_status_module | ngx_http_api_module
    STATUS_MODULE: discover

    # New users should leave this property as `true`, to identify the
    # monitored entities as `remote`. Setting this property to `false` (the
    # default value) is deprecated and will be removed soon, disallowing
    # entities that are identified as `local`.
    # Please check the documentation to get more information about local
    # versus remote entities:
    # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
    REMOTE_MONITORING: true

    # validate_certs is true by default, to avoid certificate validation connecting to a HTTPS status URL set it to false
    # VALIDATE_CERTS: true
  interval: 30s
  # labels:
  #   env: production
  #   role: load_balancer
